language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.cache/pip
    - .eggs
install:
  - pip install -e .[test]
  - pip install coveralls
script:
  - nosetests --with-coverage
  - python setup.py sdist
  - python setup.py bdist
  - python setup.py bdist_egg
after_success:
  - coveralls
sudo: false
